### PR TITLE
Add link to github for it61-rails

### PR DESCRIPTION
**Pull request by vpetrenko**

### CODE REVIEW

**Comment by lex111** [comment]
Nice catch! But maybe it's worth to do open link in a new tab?

**Comment by vpetrenko** [comment]
I don't think so. Everybody can use ctrl+click to open in new tab or whatever.

**Comment by lex111** [comment]
Well, of course the decision of the owners, but usually make opening external link in a new tab, it is good for UX, and for SEO.

**Comment by vtambourine** [comment]
I agree with @lex111. External links should open in new tab.

**Pull request merged**
